version: "3.3"
services:
  web:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.app
    restart: always
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    # volumes:
    #   - type: bind
    #     source: ../
    #     target: /usr/src/app
  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always
    networks:
      - backend
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - backend
    ports:
      - "27017:27017"

networks:
  backend:
  frontend: